---
- name: EDA | Webhook | Listen for events on a webhook
  hosts: all

 ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: EDA | Webhook | Run playbook to greet our webhook callers
      condition: event.payload is defined
      actions:
        - run_job_template:
            name: "aap-eda-greetings"
            organization: Default
            # job_args:
            #   extra_vars:
            vars:
              greeting: "{{ event.payload.message }}"
        - set_fact:
            fact:
              greeting: "{{ event.payload.message }}"
        
        # - run_job_template:
        #     name: "create-idm-user"
        #     organization: Default
            # job_args:
            #   extra_vars:
            #     user_name: "{{ event.payload.result.Account_Name[1] }}"
            #     display_name: "{{ event.payload.result.Display_Name }}"
    - name: EDA | Webhook | Run playbook to verify push
      condition: event.payload is defined
      action:
        debug: 

