---
- name: Respond to webhook POST
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6000

  rules:
    - name: Splunk Event Handler Rulebook
      condition: event.meta is defined
      actions:
        - debug:

        - run_job_template:
            name: "create-idm-user"
            organization: Default
            