---
- name: Respond to webhook POST
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6000

  rules:
    - name: R1 - Debug all
      condition: event.meta is defined
      actions:
        - debug:

        - run_job_template:
            name: "create-ipa-user"
            organization: Default
            job_args:
              extra_vars:
                user_name: "{{ event.payload.result.Account_Name[1] }}"
                display_name: "{{ event.payload.result.Display_Name }}"