- name: Playbook to handle users
  hosts: all
  vars: 
    username: "{{ ansible_eda.event.payload.result.Account_Name[1] }}"
    fullname: "{{ ansible_eda.event.payload.result.Display_Name }}"
  tasks:
  - name: Create user idm_user
    ipauser:
      ipaadmin_password: pisforpassword
      name: "{{ username }}"
      first: "{{ fullname }}"
      last: "{{ fullname }}"
      state: present

  - name: Disable the above user
    ipauser:
      ipaadmin_password: pisforpassword
      name: "{{ username }}"
      state: disabled

