- name: Playbook to handle users
  hosts: all

  tasks:
  - name: Create user idm_user
    ipauser:
      ipaadmin_password: i4info-t4tech@22
      name: idm_user1
      first: Alice1
      last: Acme1
      uid: 1000111
      gid: 10011
