---
- name: EDA | Webhook |Greeting playbook for webhook events
  hosts: all
  gather_facts: no
  tasks:
    - name: Debug message
      ansible.builtin.debug:
        # msg: "{{ greeting }}"
        msg: "{{ ansible_eda.event.payload.message }}"
